import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Footer, Navbar } from "@/components/home";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-row min-h-screen`}>
        <Navbar />
        <main className="bg-green-200 flex-1">
          <div className="h-screen overflow-y-auto">{children}</div>
        </main>
      </body>
    </html>
  );
}
